name: Rspec Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: afiso_dev
          PG_PASSWORD: afisopass
          POSTGRES_DB: postgres
          CI_HOST: localhost
        ports:
        - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      chrome:
        image: selenium/standalone-chrome:3.141.59-zirconium # this version should match that of the selenium-webdriver gem
        env:
          HUB_URL: http://chrome:4444/wd/hub
        volumes:
          - /dev/shm:/dev/shm
    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.7.2
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.2

    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev

    - name: Build DB and install gems
      env:
        PGHOST: localhost
        PGUSER: afiso_dev
        PGPORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
        RAILS_ENV: test
        CI_HOST: localhost
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bin/rails db:migrate:reset
        bin/rails db:seed
        bin/rails webpacker:install

    - name: Run tests
      env:
        PGHOST: localhost
        PGUSER: afiso_dev
        PGPORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
        RAILS_ENV: test
      run: bundle exec rspec